# Generated by Django 4.2.13 on 2024-10-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillistsubscriber',
            name='preferences',
            field=models.CharField(choices=[('weekly', 'Weekly Updates'), ('news', 'News and Important Changes'), ('all', 'I want all the emails!')], default='weekly', max_length=10),
        ),
    ]
