# Generated by Django 4.2.13 on 2024-10-17 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0002_alter_emaillistsubscriber_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='emaillistsubscriber',
            name='email',
        ),
        migrations.RemoveField(
            model_name='emaillistsubscriber',
            name='preferences',
        ),
        migrations.AddField(
            model_name='emaillistsubscriber',
            name='user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emaillistsubscriber',
            name='list_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='emails.listtype'),
            preserve_default=False,
        ),
    ]
