# Generated by Django 4.2.13 on 2024-10-21 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_sitecontactinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitecontactinfo',
            options={'verbose_name': 'Site Contact Info', 'verbose_name_plural': 'Site Contact Info'},
        ),
    ]
