# Generated by Django 4.2.13 on 2024-11-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_userprofile_email_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='member_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
