# Generated by Django 4.2.16 on 2024-10-04 21:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dcvata7jw/image/upload/v1728077686/vp82sluv7lixgq0szodx.webp', max_length=255, null=True, verbose_name='image'),
        ),
    ]
