# Generated by Django 4.2.13 on 2024-10-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_viewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alt text for image', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='image_credit',
            field=models.CharField(blank=True, help_text='Credit for the image', max_length=255),
        ),
    ]
