# Generated by Django 4.2.13 on 2024-10-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_alt_text_post_image_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Add short, relevant SEO meta description', max_length=160),
        ),
    ]
