# Generated by Django 4.2.13 on 2024-10-31 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_meta_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish_date']},
        ),
    ]
