# Generated by Django 4.2.13 on 2024-11-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_options_business_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
