# Generated by Django 4.2.13 on 2024-11-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_business_business_name_alter_business_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
