# Generated by Django 4.2.13 on 2024-11-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_business_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='alt_text',
            field=models.CharField(blank=True, default='Business image', max_length=255),
        ),
    ]
