# Generated by Django 4.2.13 on 2024-11-19 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_business_alt_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='custom_service_area',
            field=models.CharField(blank=True, help_text='Specify custom service area if not listed.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='new_service_area',
            field=models.ForeignKey(blank=True, help_text="Select a service area or specify 'Other'.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.servicearea'),
        ),
    ]
