# Generated by Django 4.2.13 on 2024-11-19 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_servicearea_business_custom_service_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='new_service_area',
        ),
        migrations.RemoveField(
            model_name='business',
            name='service_area',
        ),
        migrations.DeleteModel(
            name='ServiceArea',
        ),
    ]
