# Generated by Django 4.2.13 on 2024-11-19 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_business_service_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='business',
            name='service_area',
            field=models.ForeignKey(blank=True, help_text="Select a service area or specify 'Other'.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.servicearea'),
        ),
    ]
