# Generated by Django 4.2.13 on 2024-11-21 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0010_businessupdate_alter_business_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_owner',
            field=models.ForeignKey(blank=True, help_text='The verified owner of the business, if claimed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='is_claimed',
            field=models.BooleanField(default=False, help_text='Indicates if the business is claimed by its owner.'),
        ),
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Declined'), (3, 'Opted Out')], default=0),
        ),
    ]
