# Generated by Django 4.2.13 on 2024-11-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_business_business_owner_business_is_claimed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name_plural': 'Businesses'},
        ),
        migrations.AlterModelOptions(
            name='businessupdate',
            options={'verbose_name_plural': 'Business Updates'},
        ),
        migrations.RemoveField(
            model_name='business',
            name='is_approved',
        ),
    ]
