# Generated by Django 4.2.13 on 2024-11-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_alter_business_options_alter_businessupdate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='service_area',
            field=models.CharField(blank=True, help_text='Specify the areas this business serves (e.g., towns, cities, or regions).', max_length=255, null=True),
        ),
    ]
