# Generated by Django 4.2.13 on 2024-10-31 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ljtalks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='registration_ip',
        ),
    ]
