# Generated by Django 4.2.13 on 2024-11-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ljtalks', '0003_contactsubmission_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('terms', 'Terms and Conditions'), ('privacy', 'Privacy Policy'), ('cookies', 'Cookie Policy')], max_length=50)),
                ('content', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
