# Generated by Django 4.2.13 on 2024-11-11 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ljtalks', '0004_legaldocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legaldocument',
            name='document_type',
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='legal_document', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Add short, relevant SEO meta description', max_length=160),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='seo_tags',
            field=models.TextField(blank=True, help_text='Add your SEO keywords, separated by commas'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
