# Generated by Django 4.2.13 on 2024-11-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ljtalks', '0005_remove_legaldocument_document_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
